export interface MenuItem {
  id: number
  num?: string
  name: string
  description: string
  price: number
  image?: string
  badge?: string
  category: string
}

export interface MenuCategory {
  id: string
  name: string
  tagline: string
  items: MenuItem[]
}

export const menu: MenuCategory[] = [
  {
    id: 'beef-burgers',
    name: 'Beef Burgers',
    tagline: '100% Premium Australian Beef · Smashed on Scorching Iron',
    items: [
      {
        id: 20,
        num: '20',
        name: 'Classic Smashed',
        description: 'Australian beef patty, lettuce, tomato, fresh onion, pickles, mayo, cheese slice, caramelized onion',
        price: 699,
        category: 'beef-burgers',
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',
        badge: 'Classic Smashed',
      },
      {
        id: 21,
        num: '21',
        name: 'Smoked Sultan',
        description: 'Prime beef patty, lettuce, tomato, jalapeño, BBQ flavor, cheese slice, caramelized onion',
        price: 699,
        category: 'beef-burgers',
        image: '/images/smoked_sultan.jpg',
        badge: 'Smoky BBQ',
      },
      {
        id: 22,
        num: '22',
        name: 'Ottoman Signature',
        description: 'Prime beef patty, lettuce, tomato, unique BBQ and mayo combination, cheese, crisp-fried onion ring crown',
        price: 799,
        category: 'beef-burgers',
        image: '/images/ottoman_signature.jpg',
        badge: "Chef's Crown",
      },
      {
        id: 23,
        num: '23',
        name: 'Cheesy Overload',
        description: 'Prime beef patty, lettuce, pickle, cheese slice, deep-fried crunchy molten cheese patty, special sauce, caramelized onion',
        price: 899,
        category: 'beef-burgers',
        image: '/images/cheesy_overload.jpg',
        badge: 'Deep-Fried Cheese',
      },
      {
        id: 24,
        num: '24',
        name: 'OB Trio Mini Burger',
        description: 'A signature platter featuring 1 chicken burger and 2 beef burgers side-by-side',
        price: 749,
        category: 'beef-burgers',
        image: '/images/ob_trio_mini.jpg',
        badge: 'Trio Platter',
      },
      {
        id: 25,
        num: '25',
        name: 'Swiss Mushroom Beef',
        description: 'Prime beef patty, wild mushrooms toasted in balsamic, lettuce, pickles, cheese slice, caramelized onion',
        price: 799,
        category: 'beef-burgers',
        image: '/images/swiss_mushroom_beef.jpg',
        badge: 'Balsamic Mushroom',
      },
      {
        id: 26,
        num: '26',
        name: 'Beefchiii',
        description: 'Double powerhouse monster: Prime beef patty stacked with tender chicken strips, double cheese slice, pickles, lettuce, special sauce, BBQ sauce, cheese sauce',
        price: 999,
        category: 'beef-burgers',
        image: '/images/beefchiii.jpg',
        badge: 'Monster Monster',
      },
    ],
  },
  {
    id: 'chicken-burgers',
    name: 'Chicken Burgers',
    tagline: 'Crispy Crumbed Fillets & Flame-Grilled Stuffed Patties',
    items: [
      {
        id: 10,
        num: '10',
        name: 'Crunch Sultan',
        description: 'Crumb-fried chicken tender strips, lettuce, jalapeño, fresh onion, cheese, special sauce',
        price: 549,
        category: 'chicken-burgers',
        image: '/images/crunch_sultan.jpg',
        badge: 'Best Seller',
      },
      {
        id: 11,
        num: '11',
        name: 'OB Doner Royal',
        description: 'Authentic Turkish doner meat in toasted burger bun, lettuce, onion, pickle, cheese, twin-flavour sauce',
        price: 499,
        category: 'chicken-burgers',
        image: '/images/ob_doner_royal.jpg',
        badge: 'Doner Royal',
      },
      {
        id: 12,
        num: '12',
        name: 'Chic & Cheese',
        description: 'Fried cheese-stuffed chicken patty, cheese slice, pickles, special sauces',
        price: 599,
        category: 'chicken-burgers',
        image: '/images/chic_and_cheese.jpg',
        badge: 'Cheese Stuffed',
      },
      {
        id: 13,
        num: '13',
        name: 'Crunchezious Sultan',
        description: 'Cheetos bites, lettuce, jalapeño, fresh onion, cheese sauce, jalapeño sauce, white sauce',
        price: 699,
        category: 'chicken-burgers',
        image: '/images/crunchezious_sultan.jpg',
        badge: 'Flamin Cheetos',
      },
      {
        id: 14,
        num: '14',
        name: 'Cheesy Cheetos Beast',
        description: 'Double crunchy Cheetos fillet, lettuce, jalapeño, fresh onion, cheese sauce, jalapeño sauce, white sauce',
        price: 699,
        category: 'chicken-burgers',
        image: '/images/cheetos_beast.jpg',
        badge: 'Cheetos Beast',
      },
      {
        id: 15,
        num: '15',
        name: 'Grilled Royal',
        description: 'Flame-grilled marinated chicken fillet, lettuce, ranch sauce, peri-peri sauce, cheese slice, pickles',
        price: 699,
        category: 'chicken-burgers',
        image: '/images/grilled_royal.jpg',
        badge: 'Flame-Grilled',
      },
      {
        id: 16,
        num: '16',
        name: 'Grill & Cheese',
        description: 'Stuffed-cheese grilled patty, lettuce, pickle, salsa sauce, cheese slice and BBQ sauce',
        price: 699,
        category: 'chicken-burgers',
        image: '/images/grill_and_cheese.jpg',
        badge: 'Grilled & Stuffed',
      },
    ],
  },
  {
    id: 'doner-wraps',
    name: 'Doner & Wraps',
    tagline: 'Warm Rolled Flatbreads Stuffed with Spiced Meats & Seasoned Fries Inside',
    items: [
      {
        id: 31,
        num: '31',
        name: 'Prime Beef Wrap',
        description: 'Wrap bread, prime beef, lettuce, onion, tomato, pickle, special OB sauce, seasoned fries inside',
        price: 799,
        category: 'doner-wraps',
        image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80',
        badge: 'Prime Beef',
      },
      {
        id: 32,
        num: '32',
        name: 'Chicken Doner Wrap',
        description: 'Wrap bread, spiced chicken doner, lettuce, onion, pickles, jalapeño, tomato, garlic sauce, fries inside, special sauce',
        price: 699,
        category: 'doner-wraps',
        image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=80',
        badge: 'House Special',
      },
      {
        id: 33,
        num: '33',
        name: 'Mexican Wrap',
        description: 'Wrap bread, crispy chicken strips, lettuce, pickles, salsa sauce, special sauce, fries inside',
        price: 799,
        category: 'doner-wraps',
        image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=900&q=80',
        badge: 'Zesty Salsa',
      },
      {
        id: 34,
        num: '34',
        name: 'Crispy Chunk Wrap',
        description: 'Wrap bread, crispy fried chicken strips, lettuce, pickles, jalapeño cheese sauce, fries inside',
        price: 799,
        category: 'doner-wraps',
        image: 'https://images.unsplash.com/photo-1648787989397-6a4ec72566cb?auto=format&fit=crop&w=900&q=80',
        badge: 'Jalapeño Cheese',
      },
      {
        id: 35,
        num: '35',
        name: 'Cheetos Beef Wrap',
        description: 'Wrap bread, beef patty, Cheetos strips, lettuce, pickles, BBQ sauce, mayo sauce, ranch sauce, fries inside',
        price: 999,
        category: 'doner-wraps',
        image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80',
        badge: 'Imperial Wrap',
      },
    ],
  },
  {
    id: 'starters',
    name: 'Starters',
    tagline: 'Loaded Platters & Crumbed Chicken Bites',
    items: [
      {
        id: 1,
        num: '01',
        name: 'Crispy Tender Strips (4 Pcs)',
        description: 'Crumbed fried tender chicken strips served with honey mustard sauce',
        price: 549,
        category: 'starters',
        image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=900&q=80',
        badge: 'Honey Mustard',
      },
      {
        id: 2,
        num: '02',
        name: 'Loaded OB Fries (Chicken)',
        description: 'Fully loaded with sauce and donner chicken',
        price: 599,
        category: 'starters',
        image: '/images/loaded_ob_fries.jpg',
        badge: 'Doner Loaded',
      },
      {
        id: 3,
        num: '03',
        name: 'Loaded Crunch Fries (Chicken)',
        description: 'Fully loaded with sauce and crunchy fried chicken chunks',
        price: 599,
        category: 'starters',
        image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=900&q=80',
        badge: 'Crunch Loaded',
      },
      {
        id: 4,
        num: '04',
        name: 'Crunch Stuff Chicken Burst (4 Pcs)',
        description: 'Chicken stuffed with herbs and cheese, then crumb-fried',
        price: 449,
        category: 'starters',
        image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=900&q=80',
        badge: 'Cheese Burst',
      },
    ],
  },
  {
    id: 'peri-peri',
    name: 'Peri-Peri Grilled Chicken',
    tagline: "Nando's Style Flame-Basted Grilled Chicken Served with Fries",
    items: [
      {
        id: 110,
        num: '110',
        name: 'Quarter Peri-Peri Grilled Chicken',
        description: "Nando's style flame-grilled quarter chicken basted in spicy peri-peri marinade, served with golden hot fries",
        price: 599,
        category: 'peri-peri',
        image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=900&q=80',
        badge: 'Quarter',
      },
      {
        id: 111,
        num: '111',
        name: 'Half Peri-Peri Grilled Chicken',
        description: "Nando's style flame-grilled half chicken basted in fiery peri-peri glaze, served with golden fries",
        price: 1199,
        category: 'peri-peri',
        image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=900&q=80',
        badge: 'Half Bird',
      },
      {
        id: 112,
        num: '112',
        name: 'Full Peri-Peri Grilled Chicken',
        description: "Nando's style whole flame-grilled bird marinated 24 hours, slow-charred over open flame, served with mountain of fries",
        price: 2199,
        category: 'peri-peri',
        image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=900&q=80',
        badge: 'Imperial Feast',
      },
    ],
  },
  {
    id: 'shakes',
    name: 'Shakes',
    tagline: 'Rich, Creamy Blends Crafted with Premium Ice Cream',
    items: [
      {
        id: 60,
        num: '60',
        name: 'Oreo Shake',
        description: 'Rich crushed Oreo cookies blended with thick creamy vanilla gelato',
        price: 379,
        category: 'shakes',
        image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=900&q=80',
        badge: 'Popular',
      },
      {
        id: 61,
        num: '61',
        name: 'Caramel Blast',
        description: 'Golden caramel drizzle with thick vanilla cream',
        price: 369,
        category: 'shakes',
        image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 62,
        num: '62',
        name: 'Coco Nutella',
        description: 'Pure Italian Nutella hazelnut cocoa blended to thick creamy perfection',
        price: 369,
        category: 'shakes',
        image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 63,
        num: '63',
        name: 'Strawberry Shake',
        description: 'Fresh strawberry nectar with thick dairy cream',
        price: 369,
        category: 'shakes',
        image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 64,
        num: '64',
        name: 'Mango King',
        description: 'Luscious ripe royal mango blend with ice cream',
        price: 329,
        category: 'shakes',
        image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 65,
        num: '65',
        name: 'Espresso Vanilla',
        description: 'Bold espresso shot fused with sweet vanilla cream',
        price: 349,
        category: 'shakes',
        image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 66,
        num: '66',
        name: 'Protein Shake',
        description: 'High-protein power shake for athletes and strength',
        price: 499,
        category: 'shakes',
        image: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=900&q=80',
        badge: 'High Protein',
      },
    ],
  },
  {
    id: 'cocktails-mojitos',
    name: 'Cocktails & Mojitos',
    tagline: 'Fizzy Citrus Mocktails, Fresh Coolers & Crushed Berry Sips',
    items: [
      {
        id: 50,
        name: 'Pina Colada',
        description: 'Tropical blend of rich coconut cream & sweet pineapple',
        price: 449,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 51,
        name: 'Mint Margarita',
        description: 'Zesty refreshing crushed mint & lime margarita',
        price: 299,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80',
        badge: 'Refreshing',
      },
      {
        id: 52,
        name: 'Strawberry Margarita',
        description: 'Chilled frosty blended strawberries with fresh lime in a salted rim glass',
        price: 299,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 53,
        name: 'Lemonade',
        description: 'Fresh squeezed classic chilled citrus lemonade with lemon slices',
        price: 199,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 54,
        name: 'Spanish Margarita',
        description: 'Exotic Spanish style citrus fiesta mocktail',
        price: 610,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=900&q=80',
        badge: 'Exotic',
      },
      {
        id: 55,
        name: 'OB Sip',
        description: 'Signature Ottoman Bites house fruit infusion',
        price: 299,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?auto=format&fit=crop&w=900&q=80',
        badge: 'House Sip',
      },
      {
        id: 80,
        num: '80',
        name: 'Blue Lagoon',
        description: 'Vibrant blue curaçao citrus mocktail muddled with fresh mint, lemon wheel, and sparkling soda',
        price: 249,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 81,
        num: '81',
        name: 'Strawberry Lagoon',
        description: 'Effervescent strawberry soda cooler with fresh strawberry slices, crushed ice, and spearmint',
        price: 249,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 82,
        num: '82',
        name: 'Blueberry Mojito',
        description: 'Wild dark blueberries muddled with fresh garden mint leaves, lime wedges, and sparkling soda',
        price: 279,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 83,
        num: '83',
        name: 'Russ Berry Mojito',
        description: 'Signature ruby red raspberry blend with lemon fizz and fresh mint',
        price: 289,
        category: 'cocktails-mojitos',
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=900&q=80',
      },
    ],
  },
  {
    id: 'tea-coffee',
    name: 'Tea & Coffee',
    tagline: 'Imperial Cardamom Teas, Strong Karak Chais & Iced Brews',
    items: [
      {
        id: 90,
        num: '90',
        name: 'Cardamom Tea',
        description: 'Traditional slow-brewed tea infused with whole fragrant green cardamom pods',
        price: 149,
        category: 'tea-coffee',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=900&q=80',
        badge: 'Ottoman Royal',
      },
      {
        id: 91,
        num: '91',
        name: 'Karak Tea',
        description: 'Strong, thick, and slow-steeped dark karak chai with caramelized undertones poured hot in a glass',
        price: 100,
        category: 'tea-coffee',
        image: 'https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&w=900&q=80',
        badge: 'Karak',
      },
      {
        id: 92,
        num: '92',
        name: 'Cold Coffee',
        description: 'Creamy chilled dark roast coffee shaken with cold milk and dark chocolate shavings',
        price: 329,
        category: 'tea-coffee',
        image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 93,
        num: '93',
        name: 'Iced Latte',
        description: 'Pure double espresso poured over ice and micro-textured whole milk',
        price: 329,
        category: 'tea-coffee',
        image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 94,
        num: '94',
        name: 'Peach Iced Tea',
        description: 'Sweet peach infusion over chilled iced black tea and fresh mint',
        price: 300,
        category: 'tea-coffee',
        image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 95,
        num: '95',
        name: 'Strawberry Iced Tea',
        description: 'Crisp brewed iced tea infused with sweet strawberry compote and lemon',
        price: 300,
        category: 'tea-coffee',
        image: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=900&q=80',
      },
      {
        id: 96,
        num: '96',
        name: 'Green Apple Iced Tea',
        description: 'Tart and crisp green apple essence shaken with cold black tea',
        price: 300,
        category: 'tea-coffee',
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80',
      },
    ],
  },
  {
    id: 'extras',
    name: 'Extras & Add-ons',
    tagline: 'Customize your burger with extra patties, cheese slices, fried onions and dips',
    items: [
      { id: 40, num: '40', name: 'Beef Patty (Australian)', description: 'Extra prime Australian beef smashed patty alone on grill', price: 300, category: 'extras', image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=900&q=80' },
      { id: 41, num: '41', name: 'Fries Portion', description: 'Freshly fried golden crispy potato French fries side portion', price: 300, category: 'extras', image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80' },
      { id: 42, num: '42', name: 'Fried Onion', description: 'Crunchy golden-fried onion rings & crisps portion', price: 250, category: 'extras', image: 'https://images.unsplash.com/photo-1639024471287-032f6983cfb4?auto=format&fit=crop&w=900&q=80' },
      { id: 43, num: '43', name: 'Cheese Slice', description: 'Extra melted slices of yellow cheddar burger cheese', price: 70, category: 'extras', image: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=900&q=80' },
      { id: 44, num: '44', name: 'Sauce Dip', description: 'Choice of secret garlic mayo, BBQ, ranch, or jalapeño sauce dip cup', price: 70, category: 'extras', image: 'https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=900&q=80' },
      { id: 45, num: '45', name: 'Chicken Patty', description: 'Single extra crispy golden crumb-fried chicken cutlet patty', price: 200, category: 'extras', image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=900&q=80' },
      { id: 46, num: '46', name: 'OB Crumber Fries', description: 'Signature Ottoman Bites crumb-fried loaded fries portion', price: 450, category: 'extras', image: '/images/loaded_ob_fries.jpg' },
    ],
  },
]

export interface Review {
  name: string
  text: string | null
  textTranslated: string | null
  stars: number
  publishedAtDate: string
  isLocalGuide: boolean
  reviewerNumberOfReviews: number
  reviewerPhotoUrl: string
  responseFromOwnerText: string | null
}

export const reviews: Review[] = [
  { name: 'Honest reviews', text: 'Highly recommended Delicious food with excellent taste and quality at a reasonable price. Definitely worth trying.\n\nThe 1,000 minimum order for delivery is too high. At least within the same town, smaller orders should also be delivered. Not everyone can spend 1,000 every time. Please reconsider this policy.', textTranslated: null, stars: 5, publishedAtDate: '2026-08-03T15:24:42.344Z', isLocalGuide: true, reviewerNumberOfReviews: 29, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring to friends and family..' },
  { name: 'Summaya Rehman', text: 'Yar ma nay Kafi jaga fast food khaya lkn en ka ottoman signature Jo Burger hai woo kaaaammaaaallllll ka hai', textTranslated: "I have eaten fast food at many places but their Ottoman Signature burger is simply phenomenal!", stars: 5, publishedAtDate: '2026-08-03T07:45:47.010Z', isLocalGuide: false, reviewerNumberOfReviews: 0, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you for your love!' },
  { name: 'Zeeshan Qayyum', text: 'Kia awla wrap tha maza aa gya', textTranslated: 'What a wonderful wrap it was, absolutely mouth-watering!', stars: 5, publishedAtDate: '2026-08-01T13:59:32.095Z', isLocalGuide: false, reviewerNumberOfReviews: 1, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring' },
  { name: 'Afzaal Ali', text: 'Ambiance was good\nFood is delicious', textTranslated: null, stars: 5, publishedAtDate: '2026-07-27T15:53:21.403Z', isLocalGuide: false, reviewerNumberOfReviews: 1, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring' },
  { name: 'Muhammad Kabir Irfan Gujjar', text: 'Beautiful Place And greatest Food I Really Love it and Strongly Recommended for every one', textTranslated: null, stars: 5, publishedAtDate: '2026-07-27T04:13:54.466Z', isLocalGuide: false, reviewerNumberOfReviews: 1, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring' },
  { name: 'SALLU MELLO', text: "I ordered the cheesy beef burger and loaded fries and damn it's was good and fresh keep it up guys", textTranslated: null, stars: 5, publishedAtDate: '2026-07-24T20:38:23.653Z', isLocalGuide: true, reviewerNumberOfReviews: 23, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thanks you keep visiting and referring' },
  { name: 'Mirha Doll', text: 'Excellent Food With Great Ambiance strongly recommend for Family Dining. Great Experience', textTranslated: null, stars: 5, publishedAtDate: '2026-07-24T17:13:44.108Z', isLocalGuide: false, reviewerNumberOfReviews: 1, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring' },
  { name: 'Usman Ali', text: 'Great Place & Great Food', textTranslated: null, stars: 5, publishedAtDate: '2026-07-24T16:27:46.677Z', isLocalGuide: false, reviewerNumberOfReviews: 1, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring' },
  { name: 'Huzaifa Mukhtar', text: "Fantastic Atmosphere And Too Much Delicious Food I'm loving it And Strongly recommend For everyone", textTranslated: null, stars: 5, publishedAtDate: '2026-07-24T16:21:04.723Z', isLocalGuide: false, reviewerNumberOfReviews: 1, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring' },
  { name: 'Yasir Noor', text: "Wonderful place with very delicious food.\nStrongly Recommend for those people's who really want to eat something different", textTranslated: null, stars: 5, publishedAtDate: '2026-07-23T16:03:09.206Z', isLocalGuide: false, reviewerNumberOfReviews: 5, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank u' },
  { name: 'Hasnain Najeeb', text: 'Authentic Ottoman flavors, great vibe just keep your wallet ready', textTranslated: null, stars: 5, publishedAtDate: '2026-07-18T16:25:08.154Z', isLocalGuide: false, reviewerNumberOfReviews: 2, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring to friends and family..' },
  { name: 'Samee Ullah', text: 'Best beef burger. Better than Brim.', textTranslated: null, stars: 5, publishedAtDate: '2026-07-08T20:21:58.904Z', isLocalGuide: false, reviewerNumberOfReviews: 3, reviewerPhotoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=120&h=120&q=80', responseFromOwnerText: 'Thank you keep visiting and referring to friends and family..' },
]

export const businessInfo = {
  name: 'Ottoman Bites',
  tagline: "The Empire's Feast · Eat Like A Sultan",
  rating: 4.9,
  reviewsCount: 22,
  phone1: '0313-2707666',
  phone2: '0314-6890004',
  whatsapp: '+923132707666',
  whatsappFormatted: '+92 313 2707666',
  whatsappUrl: 'https://wa.me/923132707666',
  address: 'Shops 47, 48, 49, Gate 1, Opposite Head Office, Al-Rehman Garden, Lahore',
  fullAddress: 'Shops 47, 48, 49, Gate 1, Opposite Head Office, Al-Rehman Garden Phase 2, Lahore, Pakistan',
  mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ottoman%20Bites&query_place_id=ChIJYfhsKZIdGTkRtGQMD2hAxns',
  hours: [
    { day: 'Monday', hours: '6:00 AM – 3:00 AM' },
    { day: 'Tuesday', hours: '6:00 PM – 2:30 AM' },
    { day: 'Wednesday', hours: '6:00 PM – 2:30 AM' },
    { day: 'Thursday', hours: '6:00 PM – 2:30 AM' },
    { day: 'Friday', hours: '6:00 PM – 2:30 AM' },
    { day: 'Saturday', hours: '6:00 PM – 2:30 AM' },
    { day: 'Sunday', hours: '6:00 PM – 2:30 AM' },
  ],
  lat: 31.6005876,
  lng: 74.2338609,
}

export const heroImages = {
  burger: 'https://images.pexels.com/photos/28828554/pexels-photo-28828554.jpeg?auto=compress&cs=tinysrgb&h=1200&w=1600',
  lamps: 'https://images.pexels.com/photos/13143743/pexels-photo-13143743.jpeg?auto=compress&cs=tinysrgb&h=1200&w=1600',
  chef: 'https://images.pexels.com/photos/24205183/pexels-photo-24205183.jpeg?auto=compress&cs=tinysrgb&h=1200&w=1600',
  arches: 'https://images.pexels.com/photos/14399173/pexels-photo-14399173.jpeg?auto=compress&cs=tinysrgb&h=1200&w=1600',
  spices: 'https://images.pexels.com/photos/301669/pexels-photo-301669.jpeg?auto=compress&cs=tinysrgb&h=1200&w=1600',
  feast: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1600&q=80',
}
